### PR TITLE
renamed src/tomography/postprocess to src/tomography/postprocess_sensitivity_kernels for clarity

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 201](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/201). Fix your mistakes and push your changes back to your branch komatits/specfem3d_globe:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by komatits** [comment]
Seems to be a BuildBot issue:
make -j 8 --always-make
/home/buildbot/scripts/specfem3d_globe/compile_intel.sh: line 26: ============================: command not found

(the same issue Clément Durochat noticed the other day for SPECFEM3D).

I thus merge it manually.

**Comment by luet** [comment]
There was a mistake in the script that I fixed. But I don't think this was the reason the test failed:

    src/create_header_file/create_header_file.f90(64): internal error: Please visit    
    'http://www.intel.com/software/products/support' for assistance.
      call save_header_file(NSPEC,NGLOB,NPROC,NPROCTOT, &
    ^
    [ Aborting due to internal error. ]
    compilation aborted for src/create_header_file/create_header_file.f90 (code 1)
    make: *** [obj/create_header_file.header.o] Error 1
    make: *** Waiting for unfinished jobs....

But we have had that error before. I'll upgrade the Intel compiler, the current version is 13, hopefully that will take care of the issue.

**Pull request merged**
