### PR TITLE
replaced white spaces with tabs in src/auxiliaries/rules.mk (following a cut and paste that had converted them for some reason)

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by komatits** [comment]
BuildBot seems off, thus accepting it manually.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 169](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/169).

**Comment by komatits** [comment]
accept

On 02/04/2015 12:22 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 169
> <http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/169>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/318#issuecomment-72838951>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
