### PR TITLE
various updates and fixes

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 385](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/385). Please fix the problems and push your changes back to your branch danielpeter/specfem3d_globe:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 386](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/386).

**Comment by danielpeter** [comment]
accept

**Pull request merged**
