### PR TITLE
Vectorize interpolation for forward seismograms location

### PR DESCRIPTION
**Pull request by mpbl**
Test case:
NCHUNK = 6
NEX_* = 256
NPROC_* = 8  --> 384 processes
1266 stations
forward run with no save forward on Sandybridge CPUs
1h32m52s -> 1h20m44s

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 187](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/187). Fix your mistakes and push your changes back to your branch mpbl/specfem3d_globe:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by luet** [comment]
It looks like I have a problem with the machine where the buildbot slave
runs. I am working on it.

On Thu, Mar 5, 2015 at 8:39 AM, buildbot-princeton <notifications@github.com
> wrote:

> Your changes failed the buildbot test. See build 187
> <http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/187>.
> Fix your mistakes and push your changes back to your branch
> mpbl/specfem3d_globe:devel. This pull-request will be reopened
> automatically. You don't need to create a new pull request
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/340#issuecomment-77364641>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by luet** [comment]
We had a hardware problem. It solved now. I ran the test and they passed:
http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/188
I am going to merge the pull-request.

On Thu, Mar 5, 2015 at 9:42 AM, David Luet <luet@princeton.edu> wrote:

> It looks like I have a problem with the machine where the buildbot slave
> runs. I am working on it.
>
> On Thu, Mar 5, 2015 at 8:39 AM, buildbot-princeton <
> notifications@github.com> wrote:
>
>> Your changes failed the buildbot test. See build 187
>> <http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/187>.
>> Fix your mistakes and push your changes back to your branch
>> mpbl/specfem3d_globe:devel. This pull-request will be reopened
>> automatically. You don't need to create a new pull request
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/geodynamics/specfem3d_globe/pull/340#issuecomment-77364641>
>> .
>>
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by mpbl** [comment]
@luet 
Thanks!

**Comment by luet** [comment]
accept

On Thu, Mar 5, 2015 at 11:23 AM, David Luet <luet@princeton.edu> wrote:

> We had a hardware problem. It solved now. I ran the test and they passed:
>
> http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/188
> I am going to merge the pull-request.
>
> On Thu, Mar 5, 2015 at 9:42 AM, David Luet <luet@princeton.edu> wrote:
>
>> It looks like I have a problem with the machine where the buildbot slave
>> runs. I am working on it.
>>
>> On Thu, Mar 5, 2015 at 8:39 AM, buildbot-princeton <
>> notifications@github.com> wrote:
>>
>>> Your changes failed the buildbot test. See build 187
>>> <http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/187>.
>>> Fix your mistakes and push your changes back to your branch
>>> mpbl/specfem3d_globe:devel. This pull-request will be reopened
>>> automatically. You don't need to create a new pull request
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/geodynamics/specfem3d_globe/pull/340#issuecomment-77364641>
>>> .
>>>
>>
>>
>>
>> --
>> David Luet
>> Linux Administrator/Software & Programming Analyst
>> Department of Geosciences & PICSciE
>> Princeton University
>>
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Pull request closed without merging**
