### PR TITLE
adds new spherical harmonic model; updates OpenCL; updates element computations; introduces keyword contiguous for pointer declarations; small bug fixes

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 295](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/295). Fix your mistakes and push your changes back to your branch danielpeter/specfem3d_globe:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 296](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/296).

**Comment by komatits** [comment]
accept

On 21/04/2016 23:54, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 296
> <http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/296>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/490#issuecomment-213128178>
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
