### PR TITLE
Minor

### PR DESCRIPTION
**Pull request by ammcpherson**
I have updated the AUTHORS file to match https://github.com/geodynamics/specfem3d/issues/1531 raised by @gassmoeller. The AUTHORS file now points to /doc/USER_MANUAL/authors.tex and contains a URL to the online version of the manual.

I also changed the names of two files: README_do_not_modify_configure_directly_here_is_what_to_do_instead.txt and download_the_whole_topography_database_if_you_want_other_topographic_models.bash. They now have shorter names that should encapsulate what they do.

This is a resubmit of a previous pull request, as I accidentally tried to submit a pull request to the master branch

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 467](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/467). Please fix the problems and push your changes back to your branch ammcpherson/specfem3d_globe:minor. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by gassmoeller** [comment]
Hi @ammcpherson thanks a lot for the contributions, they look great. @danielpeter I have some trouble accessing the buildbot output to understand why the buildbot test failed. I can reach the website http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/467, but I cannot access any actual error message. Do you know what is going on?

**Comment by danielpeter** [comment]
not sure what buildbot has, probably crashed due to today's stress test :) 

will merge manually...

**Pull request merged**
