### PR TITLE
Updated Laplacian smoothing

### PR DESCRIPTION
**Pull request by icui**
1. corrected the smoothing length (previously the input parameters sigma_h and sigma_v were lengths in x and z direction, now changed to horizontal and vertical direction).
2. added an option to change vertical smoothing length sigma_v at a given depth range, enabling users to use a smaller vertical length in crust and upper mantle only.
3. depth-dependent smoothing length is now relative to the PREM model instead of the 3D velocity model which eliminates horizontal variation in smoothing length.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 422](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/422). Please fix the problems and push your changes back to your branch icui/specfem3d_globe:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 423](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/423). Please fix the problems and push your changes back to your branch icui/specfem3d_globe:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 425](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/425). Please fix the problems and push your changes back to your branch icui/specfem3d_globe:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by danielpeter** [comment]
closing PR due to failing tests

please check the file compilation dependency for `xsmooth_laplacian**` targets. you might need to add something like:
```
$O/laplacian_smoothing_sem.postprocess.o: $O/meshfem3D_par.check_module.o
$O/laplacian_smoothing_sem.postprocess_adios.o: $O/meshfem3D_par.check_module.o
```
to the corresponding `rules.mk` file

**Pull request closed without merging**
