### PR TITLE
moved src/postprocess into src/tomography following a developers meeting at EGU this week (to Ryan: we will explain; basically this will make future developments simpler)

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 200](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/200).

**Comment by komatits** [comment]
accept

On 04/18/2015 06:44 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 200
> <http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/200>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/361#issuecomment-94179911>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by danielpeter** [comment]
hi Dimitri,

moving postprocess into src/tomography breaks the recognition of make targets. with the current Makefile, only targets in sub-directories of src/ are found, but not sub-sub-directories. you can test e.g. with "make xclip_sem". related to it, the cleaning of binaries is not working anymore for the postprocess tools, they stay in bin/ after calling "make clean". easiest way to fix would be to move it back into src/ directory...

best wishes,
daniel

**Comment by komatits** [comment]
Hi Daniel, Hi all,

Thanks! It is probably not too difficult to fix the Makefile. Does 
anybody know how to do that?

To summarize what the small problem is: we moved one directory 
("postprocess") into another ("tomography") and also renamed it 
"postprocess_sensitivity_kernels". I thought I had updated the Makefile 
accordingly, the code compiles fine but there are apparently side 
effects when doing "make clean".

PS: this applies to 2D, 3D, and 3D_GLOBE.

Thanks,
Dimitri.

On 04/28/2015 10:29 AM, daniel peter wrote:
> hi Dimitri,
>
> moving postprocess into src/tomography breaks the recognition of make
> targets. with the current Makefile, only targets in sub-directories of
> src/ are found, but not sub-sub-directories. you can test e.g. with
> "make xclip_sem". related to it, the cleaning of binaries is not working
> anymore for the postprocess tools, they stay in bin/ after calling "make
> clean". easiest way to fix would be to move it back into src/ directory...
>
> best wishes,
> daniel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/361#issuecomment-96972557>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by danielpeter** [comment]
fixed by PR #376 for the global version

**Pull request merged**
