### PR TITLE
Fix typo in ignore paths.

### PR DESCRIPTION
**Pull request by QuLogic**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed do not require a buildbot test. The maintainers can commit these changes.

**Comment by komatits** [comment]
accept

On 05/21/2015 09:41 PM, buildbot-princeton wrote:
> The files changed do not require a buildbot test. The maintainers can
> commit these changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/389#issuecomment-104399286>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by danielpeter** [comment]
actually, we have all these Makefiles which would be nice be included in git versioning:
./src/auxiliaries/Makefile
./src/create_header_file/Makefile
./src/meshfem3D/Makefile
./src/shared/Makefile
./src/specfem3D/Makefile
./src/tomography/Makefile
./src/tomography/postprocess_sensitivity_kernels/Makefile

the ignore path ./Makefile was only to exclude the top-level one which is the only one created from Makefile.in by the configuration script. removing the dot in the ignore path will likely remove all Makefiles from version control again...

**Comment by QuLogic** [comment]
No, it doesn't. The leading `/` signifies an absolute path. Putting the `.` in the front doesn't actually ignore the top-level file.

**Comment by danielpeter** [comment]
okay great, if so then it will be what we want :)

**Pull request merged**
