### PR TITLE
adds new sglobe-rani model; uses tiso computation for crustal/upper mantle elements

### PR DESCRIPTION
**Pull request by danielpeter**
same PR again, including some code cleaning

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The following files in your commit contain non-ASCII characters:
src/meshfem3D/model_sglobe.f90
This message is a warning only as this will be fixed by the automatic run of the code beautifier
Under Linux, one way to check for non-ASCII characters is:
grep --color='auto' -P -n "[\x80-\xFF]" src/meshfem3D/model_sglobe.f90
This will give you the line number, and will highlight non-ASCII chars in red.

To convert the non-ASCII characters automatically, under Linux, you can use:
iconv -f utf-8 -t ASCII//TRANSLIT src/meshfem3D/model_sglobe.f90-o src/meshfem3D/model_sglobe.f90
Although you should be aware that some characters won't be converted properly.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
There was an error running buildbot. The system administrator needs to look into it

**Comment by buildbot-princeton** [comment]
The following files in your commit contain non-ASCII characters:
src/meshfem3D/model_sglobe.f90
This message is a warning only as this will be fixed by the automatic run of the code beautifier
Under Linux, one way to check for non-ASCII characters is:
grep --color='auto' -P -n "[\x80-\xFF]" src/meshfem3D/model_sglobe.f90
This will give you the line number, and will highlight non-ASCII chars in red.

To convert the non-ASCII characters automatically, under Linux, you can use:
iconv -f utf-8 -t ASCII//TRANSLIT src/meshfem3D/model_sglobe.f90-o src/meshfem3D/model_sglobe.f90
Although you should be aware that some characters won't be converted properly.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 377](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/377).

**Comment by danielpeter** [comment]
accept.

**Pull request merged**
