### PR TITLE
updates configuration and optimizes arrays for OpenMP and MIC

### PR DESCRIPTION
**Pull request by danielpeter**
based on a contribution by Piero Lanucara and Vittorio Ruggiero

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 291](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/291). Fix your mistakes and push your changes back to your branch danielpeter/specfem3d_globe:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 292](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/292).

**Comment by danielpeter** [comment]
accept

**Pull request merged**
