### PR TITLE
adios update and kernel bug fix

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 298](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/298).

**Comment by komatits** [comment]
accept

On 20/05/2016 02:06, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 298
> <http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/298>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/493#issuecomment-220484262>
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by danielpeter** [comment]
accept

**Pull request merged**
