### PR TITLE
updates gladm25 model routines; adds SPiRaL v1.4 model; updates GPU routines (new tiso routine & async memory copies)

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The following files in your commit contain non-ASCII characters:
src/meshfem3D/model_spiral.f90
This message is a warning only as this will be fixed by the automatic run of the code beautifier
Under Linux, one way to check for non-ASCII characters is:
grep --color='auto' -P -n "[\x80-\xFF]" src/meshfem3D/model_spiral.f90
This will give you the line number, and will highlight non-ASCII chars in red.

To convert the non-ASCII characters automatically, under Linux, you can use:
iconv -f utf-8 -t ASCII//TRANSLIT src/meshfem3D/model_spiral.f90-o src/meshfem3D/model_spiral.f90
Although you should be aware that some characters won't be converted properly.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 427](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/427).

**Comment by danielpeter** [comment]
accept


On 24 Aug 2021, at 1:02 PM, buildbot-princeton ***@***.******@***.***>> wrote:



Your changes passed the buildbot test. See build 427<https://urldefense.com/v3/__http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/427__;!!Nmw4Hv0!mJkci_jGoK7kS9lnTZ00qBio0FH9o7ts1-EsoLE4FyCRwprUCvL9rfih28GFO06BnM-yIg$>.

**Pull request merged**
