### PR TITLE
reverted change by @taotaokai, who had changed the rotation matrix to its transpose, because Qinya Liu says the original implementation is the right one

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 278](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/278).

**Comment by komatits** [comment]
accept

On 02/16/2016 04:54 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 278
> <http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/278>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/467#issuecomment-184743065>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by taotaokai** [comment]
Hi, @liuqinya @komatits 

Thank you for your comments. But let us do it more explicitly with index notation here:

let M' be the representation of the moment tensor in the local coordinate system and M in the global system, and let Nu be the rotation matrix that transforms coordinates from the global system (x,y,z) to the local coordinate system (N,E,V), we have

M'_ij = Nu_ik * M_kl * trans(Nu)_lj

M_kl = trans(Nu)_ki * M'_ij * Nu_jl

, supplied that **trans(Nu) = inv(Nu)** (inv() is the invert of a matrix, trans() is the tranpose of a matrix).

Let dF/dM'_ij be the partial derivative of the misfit function F to M'_ij, then from the chain rule we have

dF/dM'_ij 

= dF/dM_kl * dM_kl/dM'_ij

= dF/dM_kl * trans(Nu)_ki * Nu_jl

= Nu_ik * dF/dM_kl * trans(Nu)_lj

, in the concise form 

dF/dM' = Nu * dF/dM * trans(Nu)

, which is exactly the same as the transformation for the moment tensor. The difference in the transformation rules between vector and covector is gone because **trans(inv(Nu)) = Nu**, in which trans(inv(Nu)) is the transformation matrix for the covector (like the gradient here).

**Comment by komatits** [comment]
Hi @taotaokai ,

Thanks!
I have opened a new Git issue: 
https://github.com/geodynamics/specfem3d_globe/issues/468

Could you please send us the synthetic case that confirms the problem 
and that you mentioned in your first email?

Thanks,
Dimitri.

On 16/02/2016 23:40, taotaokai wrote:
> Hi, @liuqinya <https://github.com/liuqinya> @komatits
> <https://github.com/komatits>
>
> Thank you for your comments. But let us do it more explicitly with index
> notation here:
>
> let M' be the representation of the moment tensor in the local
> coordinate system and M in the global system, and let Nu be the rotation
> matrix that transforms coordinates from the global system (x,y,z) to the
> local coordinate system (N,E,V), we have
>
> M'_ij = Nu_ik * M_kl * trans(Nu)_lj
>
> M_kl = trans(Nu)_ki * M'_ij * Nu_jl
>
> , supplied that *trans(Nu) = inv(Nu)* (inv() is the invert of a matrix,
> trans() is the tranpose of a matrix).
>
> Let dF/dM'_ij be the partial derivative of the misfit function F to
> M'_ij, then from the chain rule we have
>
> dF/dM'_ij
>
> = dF/dM_kl * dM_kl/dM'_ij
>
> = dF/dM_kl * trans(Nu)_ki * Nu_jl
>
> = Nu_ik * dF/dM_kl * trans(Nu)_lj
>
> , in the concise form
>
> dF/dM' = Nu * dF/dM * trans(Nu)
>
> , which is exactly the same as the transformation for the moment tensor.
> The difference in the transformation rules between vector and covector
> is gone because *trans(inv(Nu)) = Nu*, in which trans(inv(Nu)) is the
> transformation matrix for the covector (like the gradient here).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/467#issuecomment-184904235>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
