### PR TITLE
updates array allocations

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 391](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/391). Please fix the problems and push your changes back to your branch danielpeter/specfem3d_globe:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 392](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/392).

**Comment by danielpeter** [comment]
accept



On 11 Aug 2020, at 10:15 PM, buildbot-princeton <notifications@github.com<mailto:notifications@github.com>> wrote:



Your changes passed the buildbot test. See build 392<http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/392>.

**Pull request merged**
