### PR TITLE
adds more adios wrapper function

### PR DESCRIPTION
**Pull request by danielpeter**
will make it easier to add ADIOS support in tomo tools

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 289](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/289). Fix your mistakes and push your changes back to your branch danielpeter/specfem3d_globe:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 290](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/290).

**Comment by danielpeter** [comment]
accept

**Comment by komatits** [comment]
accept

On 28/03/2016 18:16, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 290
> <http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/290>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/486#issuecomment-202466946>
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
