### PR TITLE
Check averaged isotropic shear wavespeed computations for all models.

### PR DESCRIPTION
**Pull request by 1sbeller**
Lucas has found other occurences of the problem we corrected yesterday.
Aside note: would it make sense to write a utility function get_isotropic_average to encapsulate this instead of explicitly checking everytwhere in the code?
Stephen

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The following files in your commit contain non-ASCII characters:
src/meshfem3D/meshfem3D_models.F90
This message is a warning only as this will be fixed by the automatic run of the code beautifier
Under Linux, one way to check for non-ASCII characters is:
grep --color='auto' -P -n "[\x80-\xFF]" src/meshfem3D/meshfem3D_models.F90
This will give you the line number, and will highlight non-ASCII chars in red.

To convert the non-ASCII characters automatically, under Linux, you can use:
iconv -f utf-8 -t ASCII//TRANSLIT src/meshfem3D/meshfem3D_models.F90-o src/meshfem3D/meshfem3D_models.F90
Although you should be aware that some characters won't be converted properly.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 381](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/381). Please fix the problems and push your changes back to your branch 1sbeller/specfem3d_globe:patch-1. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 382](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/382). Please fix the problems and push your changes back to your branch 1sbeller/specfem3d_globe:patch-1. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 383](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/383). Please fix the problems and push your changes back to your branch 1sbeller/specfem3d_globe:patch-1. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 384](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/384). Please fix the problems and push your changes back to your branch 1sbeller/specfem3d_globe:patch-1. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by danielpeter** [comment]
merging manually. compiler test fails on intel, to fix later.

**Comment by danielpeter** [comment]
> Aside note: would it make sense to write a utility function get_isotropic_average to encapsulate this instead of explicitly checking everytwhere in the code?

we could, just need to make sure the get_model() routine doesn't slow down too much as this one is the most heavy one. thus, this utility function get_isotropic_average should go into the same code file as get_model() to help fortran compilers inline the function.

**Pull request merged**
