### PR TITLE
adds a cross-section (postprocessing) tool and fixes configure scripts for cross-compilation 

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 250](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/250). Fix your mistakes and push your changes back to your branch danielpeter/specfem3d_globe:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 251](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/251).

**Comment by danielpeter** [comment]
accept

**Pull request merged**
