### PR TITLE
Solve mesher crash on power9 architectures

### PR DESCRIPTION
**Pull request by 1sbeller**
Add absolute value of argument to avoid square root of slightly negative values.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 379](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/379). Please fix the problems and push your changes back to your branch 1sbeller/specfem3d_globe:patch-1. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by danielpeter** [comment]
maybe an issue with a multiline statement in abs(..)?

**Comment by 1sbeller** [comment]
Hi Daniel,
Well, that's probably the case.
Stephen

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 380](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/380). Please fix the problems and push your changes back to your branch 1sbeller/specfem3d_globe:patch-1. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by danielpeter** [comment]
well, that’s something else that i just fixed in my local repo. ok, let me submit this together with some more changes i recently made.
-daniel

**Comment by 1sbeller** [comment]
Great! Seems to pass :)

**Comment by danielpeter** [comment]
merging manually. works on gcc, will submit a fix for intel compilation asap.

**Pull request merged**
