### PR TITLE
changed GPU_DEVICE string from 12 to 120 characters

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
There was an error running buildbot. The system administrator needs to look into it

**Comment by komatits** [comment]
BuildBot crashed, thus merging it manually.

**Comment by luet** [comment]
It’s fixed now.
Best,
David

**Comment by komatits** [comment]
This change was not from me, it was a commit I made after receiving a patch file from a user. But with Matthieu's change it looks OK now.
Dimitri.

**Pull request merged**
