### PR TITLE
Add the writer for the hdf5 ASDF and deleted the adios ASDF

### PR DESCRIPTION
**Pull request by jas11**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 244](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/244). Fix your mistakes and push your changes back to your branch jas11/specfem3d_globe:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by QuLogic** [comment]
Cool, but I think there are a few extraneous changes here:
 * Why change the default `CMTSOLUTION`, `Par_file` and `STATIONS`?
 * You added a pre-build `libasdf.a` that's not going to work on a majority of other machines. The dependency should be checked in `configure.ac` just like the others.
 * There's a `Makefile` rule depending on some absolute path on your system, which obviously is not portable.

**Comment by jas11** [comment]
On Aug 26, 2015, at 5:09 PM, Elliott Sales de Andrade <notifications@github.com<mailto:notifications@github.com>> wrote:


Cool, but I think there are a few extraneous changes here:

  *   Why change the default CMTSOLUTION, Par_file and STATIONS?

Didn’t mean to do this, changed them back.

  *   You added a pre-build libasdf.a that's not going to work on a majority of other machines. The dependency should be checked in configure.ac just like the others.

Yeah, I also had it set up to force users to build asdf. Making it a dependency.

  *   There's a Makefile rule depending on some absolute path on your system, which obviously is not portable.

Yeah, now setting it up as —with-asdf=$PATH in the configure.

Thanks for the help.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 245](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/245). Fix your mistakes and push your changes back to your branch jas11/specfem3d_globe:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by jas11** [comment]
The library path is provided via ./configure --with-asdf ASDF_LIB=$TARGET
This assumes libasdf.a is built for the right architecture. The other compiler flags are in the rules.mk for specfem3D. It works on my machine, but buildbut is failing on the setup/version.fh still.
I removed the comments from the ADIOS stuff.

**Comment by jas11** [comment]
Yeah, I am using a static ASDF library so I did need them for compiling. I guess an ASDF macro would be useful for confirming these things work for specfem.

**Comment by luet** [comment]
ASDF not being installed on the buildbot host is going to be a problem. But
it's not the reason for the compile failure.
If you follow the  link for the build
<http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/245/steps/--enable-double-precision_make/logs/stdio>

make: *** No rule to make target `@GIT_VERSION_DEPS@', needed by
`setup/version.fh'.  Stop.
make: *** Waiting for unfinished jobs....


On Thu, Aug 27, 2015 at 4:19 PM, James Smith <notifications@github.com>
wrote:

> The library path is provided via ./configure --with-asdf ASDF_LIB=$TARGET
> This assumes libasdf.a is built for the right architecture. The other
> compiler flags are in the rules.mk for specfem3D. It works on my machine,
> but buildbut is failing on the setup/version.fh still.
> I removed the comments from the ADIOS stuff.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/430#issuecomment-135541394>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by QuLogic** [comment]
It's strange though, I don't see `@GIT_VERSION_DEPS@` anywhere in the diff.

**Comment by luet** [comment]
It's in the `Makefile.in` (L 351):

    ${SETUP}/version.fh: @GIT_VERSION_DEPS@
        @echo "GEN $@"
        @echo "! This file is generated by Make. Do not edit this file!" > $@
        @echo "character(len=*), parameter :: git_version = \"$$(cd ${S_TOP} && git describe --tags)\"" >> $@

I am looking. It might be some environment variables.

**Comment by luet** [comment]
@QuLogic I think you should remember where this comes from: 45378573
Any hint as to what the problem might be?

**Comment by luet** [comment]
Here are the steps, from a fresh clone:

    $ git checkout -b jas11-devel devel
    $ git pull https://github.com/jas11/specfem3d_globe.git devel
    $ git submodule init
    $ git submodule update
    $ ./configure FC=gfortran CC=gcc MPIFC=mpif90 MPICC=mpicc --with-mpi --enable-double-precision

Then I compile with 

    make -j 8

I get the error:

    gfortran -g -O2  -std=gnu -fimplicit-none -frange-check -fmax-errors=10 -pedantic -pedantic-errors -Waliasing -Wampersand -Wcharacter-truncation -Wline-truncation -Wsurprising -Wno-tabs -Wunderflow -ffpe-trap=invalid,zero,overflow -Wunused -Werror -O3 -DFORCE_VECTORIZATION -J./obj -I./obj -I.  -I. -I./setup -c -o obj/shared_par.shared_module.o src/shared/shared_par.f90
    gcc -c -I./setup  -DFORCE_VECTORIZATION  -g -O2 -o obj/param_reader.cc.o src/shared/param_reader.c 
    gcc -c -I./setup  -DFORCE_VECTORIZATION  -g -O2 -o obj/binary_c_io.cc.o src/shared/binary_c_io.c 
    gcc -c -I./setup  -DFORCE_VECTORIZATION  -g -O2 -o obj/adios_method_stubs.cc.o src/shared/adios_method_stubs.c 
    make: *** No rule to make target `@GIT_VERSION_DEPS@', needed by `setup/version.fh'.  Stop.
    make: *** Waiting for unfinished jobs....

Note that a serial `make` gives the same error.

I am compiling with GNU compilers:

    gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC)

and `GNU Make 3.81` and git 1.8.3.1.

**Comment by jas11** [comment]
When I run the following steps after updating the submodule:

aclocal -I m4
autoconf -I m4

the error goes away. Can you try this?

On Aug 28, 2015, at 10:51 AM, David Luet <notifications@github.com<mailto:notifications@github.com>> wrote:


Here are the steps, from a fresh clone:

$ git checkout -b jas11-devel devel
$ git pull https://github.com/jas11/specfem3d_globe.git devel
$ git submodule init
$ git submodule update
$ ./configure FC=gfortran CC=gcc MPIFC=mpif90 MPICC=mpicc --with-mpi --enable-double-precision


Then I compile with

make -j 8


I get the error:

gfortran -g -O2  -std=gnu -fimplicit-none -frange-check -fmax-errors=10 -pedantic -pedantic-errors -Waliasing -Wampersand -Wcharacter-truncation -Wline-truncation -Wsurprising -Wno-tabs -Wunderflow -ffpe-trap=invalid,zero,overflow -Wunused -Werror -O3 -DFORCE_VECTORIZATION -J./obj -I./obj -I.  -I. -I./setup -c -o obj/shared_par.shared_module.o src/shared/shared_par.f90
gcc -c -I./setup  -DFORCE_VECTORIZATION  -g -O2 -o obj/param_reader.cc.o src/shared/param_reader.c
gcc -c -I./setup  -DFORCE_VECTORIZATION  -g -O2 -o obj/binary_c_io.cc.o src/shared/binary_c_io.c
gcc -c -I./setup  -DFORCE_VECTORIZATION  -g -O2 -o obj/adios_method_stubs.cc.o src/shared/adios_method_stubs.c
make: *** No rule to make target `@GIT_VERSION_DEPS@', needed by `setup/version.fh'.  Stop.
make: *** Waiting for unfinished jobs....


Note that a serial make gives the same error.

I am compiling with GNU compilers:

gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC)


and GNU Make 3.81 and git 1.8.3.1.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 246](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/246). Fix your mistakes and push your changes back to your branch jas11/specfem3d_globe:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 247](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/247). Fix your mistakes and push your changes back to your branch jas11/specfem3d_globe:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by luet** [comment]
Running aclocal and autoconf fixed that problem. I thought I had tried
before but I clearly didn't.
Now there is a problem with the compile with cuda. I'll look into it.

On Fri, Aug 28, 2015 at 12:44 PM, buildbot-princeton <
notifications@github.com> wrote:

> Your changes failed the buildbot test. See build 247
> <http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/247>.
> Fix your mistakes and push your changes back to your branch
> jas11/specfem3d_globe:devel. This pull-request will be reopened
> automatically. You don't need to create a new pull request
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/430#issuecomment-135829051>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 248](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/248).

**Comment by QuLogic** [comment]
Bleh, that's why I don't like auto-generated files in VCS; they get outdated or misgenerated. It looks like you had an old copy of `configure` in this branch earlier?

**Comment by komatits** [comment]
accept

On 08/28/2015 09:15 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 248
> <http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/248>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/430#issuecomment-135863750>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by jas11** [comment]
Yup

On Aug 28, 2015 5:23 PM, Elliott Sales de Andrade <notifications@github.com> wrote:

Bleh, that's why I don't like auto-generated files in VCS; they get outdated or misgenerated. It looks like you had an old copy of configure in this branch earlier?

**Pull request merged**
