### PR TITLE
updates user manual for wiki pages

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed do not require a buildbot test. The maintainers can commit these changes.

**Comment by danielpeter** [comment]
accept

**Comment by komatits** [comment]
Thanks!

It seems the ./translate_user_manual_to_markdown.pl script is not in the 
commit (it is used by 
doc/USER_MANUAL/translate_LaTeX_manual_to_wiki_markdown.sh but does not 
seem to be included).

Thanks,
Dimitri.

On 04/27/2015 01:37 PM, daniel peter wrote:
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/geodynamics/specfem3d_globe/pull/373
>
>
>         Commit Summary
>
>   * updates user manual to be translatable by pandoc
>   * adds translate script for wiki generation
>
>
>         File Changes
>
>   * *M* doc/USER_MANUAL/03_running_the_mesher.tex
>     <https://github.com/geodynamics/specfem3d_globe/pull/373/files#diff-0>
>     (10)
>   * *M* doc/USER_MANUAL/bibliography.bib
>     <https://github.com/geodynamics/specfem3d_globe/pull/373/files#diff-1>
>     (6)
>   * *M* doc/USER_MANUAL/manual_SPECFEM3D_GLOBE.pdf
>     <https://github.com/geodynamics/specfem3d_globe/pull/373/files#diff-2>
>     (0)
>   * *A* doc/USER_MANUAL/translate_LaTeX_manual_to_wiki_markdown.sh
>     <https://github.com/geodynamics/specfem3d_globe/pull/373/files#diff-3>
>     (22)
>
>
>         Patch Links:
>
>   * https://github.com/geodynamics/specfem3d_globe/pull/373.patch
>   * https://github.com/geodynamics/specfem3d_globe/pull/373.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/373>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by danielpeter** [comment]
hi Dimitri, 

the translate script is in the wiki repository. you can clone it by:
git clone https://github.com/geodynamics/specfem3d_globe.wiki.git

best wishes,
daniel

**Comment by komatits** [comment]
Hi Daniel,

Thanks a lot!
I have added it (i.e. added git checkout) to the script.

Best wishes,
Dimitri.

On 04/28/2015 09:10 AM, daniel peter wrote:
> hi Dimitri,
>
> the translate script is in the wiki repository. you can clone it by:
> git clone https://github.com/geodynamics/specfem3d_globe.wiki.git
>
> best wishes,
> daniel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/373#issuecomment-96953789>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
