### PR TITLE
makes static compilation optional (by default turned off)

### PR DESCRIPTION
**Pull request by danielpeter**
with this change, there is no need to recompile the code anymore when running different simulation setups/examples (given it is compiled with the appropriate feature set enabled, like cuda/hip/opencl, adios, asdf, openmp and others; the solver will read by runtime the mesh parameter setup, now output by xmeshfem3d)

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 458](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/458). Please fix the problems and push your changes back to your branch danielpeter/specfem3d_globe:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 459](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/459).

**Comment by danielpeter** [comment]
accept


On Apr 8, 2022, at 21:08, buildbot-princeton ***@***.***> wrote:

﻿

Your changes passed the buildbot test. See build 459<https://urldefense.com/v3/__http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/459__;!!Nmw4Hv0!zZsUsJOvhiO3FXvRp-m3D55ZkgeyqhvkiB6YTRnmMS0IGal2_lE_4p9vYhjolcvmcBKkgP-3btGBebGC6cgQH3lNoPtQYYI$>.

**Pull request merged**
