### PR TITLE
updates files in m4/

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Only pulls towards the devel branch are accepted, you are trying to push towards devel_7.0.0.RC.

**Comment by luet** [comment]
@danielpeter would you like to create a branch on the central repo for your
RC that is watched by buildbot? I am happy to help.
Best,
David

On Wed, Mar 11, 2015 at 4:03 AM, buildbot-princeton <
notifications@github.com> wrote:

> Closed #347 <https://github.com/geodynamics/specfem3d_globe/pull/347>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/347#event-249912904>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by danielpeter** [comment]
hi David, 

thanks, but i will work around it :) 

as a maintainer of the package i can create the temporary branch on the central repo myself and commit directly to it. that's what i'm doing at the moment. this avoids setting up buildbot for this temporary branch. and then once i finished cleaning up the branch, i will do a final merge into devel to have buildbot take a look at it as well. this should be fine as a work-around.

best wishes,
daniel

**Comment by luet** [comment]
That sounds good.
Best,
David

On Wed, Mar 11, 2015 at 9:17 AM, daniel peter <notifications@github.com>
wrote:

> hi David,
>
> thanks, but i will work around it :)
>
> as a maintainer of the package i can create the temporary branch on the
> central repo myself and commit directly to it. that's what i'm doing at the
> moment. this avoids setting up buildbot for this temporary branch. and then
> once i finished cleaning up the branch, i will do a final merge into devel
> to have buildbot take a look at it as well. this should be fine as a
> work-around.
>
> best wishes,
> daniel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/347#issuecomment-78260523>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Pull request closed without merging**
