### PR TITLE
Vectorizes seismogram interpolation

### PR DESCRIPTION
**Pull request by mpbl**
Test case:
NCHUNK = 6
NEX_* = 256
NPROC_* = 8 --> 384 processes
1266 stations
forward run with no save forward on Sandybridge CPUs
1h32m52s -> 1h20m44s

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 189](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/189).

**Comment by mpbl** [comment]
accept

**Comment by komatits** [comment]
accept

On 03/05/2015 09:58 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 189
> <http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/189>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/341#issuecomment-77450211>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
