### PR TITLE
Write 't_c_source' adios variable in the same case than its definition

### PR DESCRIPTION
**Pull request by mpbl**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 166](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/166).

**Comment by mpbl** [comment]
On 01/29/2015 03:16 PM, buildbot-princeton wrote:
>
> Your changes passed the buildbot test. See build 166 
> <http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/166>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/geodynamics/specfem3d_globe/pull/313#issuecomment-72096035>.
>
accept

**Comment by mpbl** [comment]
accept

**Pull request merged**
