### PR TITLE
small updates

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 223](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/223).

**Comment by danielpeter** [comment]
accept

**Comment by komatits** [comment]
accept

On 05/18/2015 02:58 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 223
> <http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/223>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/383#issuecomment-103051580>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
