### PR TITLE
merges changes from RC into devel version

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Your changes cannot be merged with a fast-forward merge.
This indicates that your repo is out of sync with the central repo.
If you are using hub, do:
$ git pull
If your are note using hub, do:
$ git pull upstream devel
Then open a new pull-request.

**Comment by buildbot-princeton** [comment]
The files changed do not require a buildbot test. The maintainers can commit these changes.

**Comment by luet** [comment]
For the record, we constrain pull-requests to be not only mergeable (which is the status given on the web page) but that it is so with a fast-forward merge. When pull-request can't be merged with a fast-forward, it's usually an indication that the developer has not updated his/her branch (git pull) before opening the pull-request.

I don't know exactly what the problem was with this PR, the buildbot logs show an error message when it tried to "git pull --ff-only". And things have changed between #375 and #376 : all the SHA1 hashes have changed. So I am not sure this was a false alert.

There was a bug that caused it to post the second message ("The files changed do not ..."). I just fixed it.

**Comment by luet** [comment]
Often what happens is developers forget to pull the changes made when buildbot runs the code beautifier (as in 2b79b891aa). I think it's because they are less visible since there is no notification for them. The best way is to run a "git pull" every time before opening a pull-request.

**Pull request closed without merging**
