### PR TITLE
Merged the previous ASDF commit for where ASDF files are saved to devel branch

### PR DESCRIPTION
**Pull request by jas11**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 254](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/254).

**Comment by QuLogic** [comment]
FYI, you can avoid the merge by doing `git fetch && git rebase -i upstream/devel` or `git pull --rebase`. Though it's too late now that Buildbot's got a frozen version of this one.

**Comment by komatits** [comment]
accept

On 09/22/2015 10:57 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 254
> <http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/254>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/438#issuecomment-142419249>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
