### PR TITLE
Mars addition

### PR DESCRIPTION
**Pull request by danielpeter**
see EXAMPLE/mars_regional/ for a regional simulation on mars

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The following files in your commit contain non-ASCII characters:
EXAMPLES/mars_regional/REF_SEIS/constants.h
setup/constants.h.in
src/shared/model_Sohl.f90
This message is a warning only as this will be fixed by the automatic run of the code beautifier
Under Linux, one way to check for non-ASCII characters is:
grep --color='auto' -P -n "[\x80-\xFF]" EXAMPLES/mars_regional/REF_SEIS/constants.h
This will give you the line number, and will highlight non-ASCII chars in red.

To convert the non-ASCII characters automatically, under Linux, you can use:
iconv -f utf-8 -t ASCII//TRANSLIT EXAMPLES/mars_regional/REF_SEIS/constants.h-o EXAMPLES/mars_regional/REF_SEIS/constants.h
Although you should be aware that some characters won't be converted properly.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 378](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/378).

**Comment by danielpeter** [comment]
accept

**Pull request merged**
