### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by jas11**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by komatits** [comment]
Hi all,

It seems BuildBot is partly down and that pull request never went through.

Best,
Dimitri.

On 26/02/2016 05:07, buildbot-princeton wrote:
> The files changed require a buildbot test. Buildbot has started.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/472#issuecomment-189102202>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by luet** [comment]
I am working on it.
David

On Fri, Feb 26, 2016 at 6:06 AM, Dimitri Komatitsch <
notifications@github.com> wrote:

>
> Hi all,
>
> It seems BuildBot is partly down and that pull request never went through.
>
> Best,
> Dimitri.
>
> On 26/02/2016 05:07, buildbot-princeton wrote:
> > The files changed require a buildbot test. Buildbot has started.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/geodynamics/specfem3d_globe/pull/472#issuecomment-189102202
> >.
> >
>
> --
> Dimitri Komatitsch
> CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
> UPR 7051, Marseille, France http://komatitsch.free.fr
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/472#issuecomment-189223114>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by komatits** [comment]
Thanks!

Dimitri.

On 26/02/2016 16:12, David Luet wrote:
> I am working on it.
> David
>
> On Fri, Feb 26, 2016 at 6:06 AM, Dimitri Komatitsch <
> notifications@github.com> wrote:
>
>  >
>  > Hi all,
>  >
>  > It seems BuildBot is partly down and that pull request never went
> through.
>  >
>  > Best,
>  > Dimitri.
>  >
>  > On 26/02/2016 05:07, buildbot-princeton wrote:
>  > > The files changed require a buildbot test. Buildbot has started.
>  > >
>  > > —
>  > > Reply to this email directly or view it on GitHub
>  > > <
>  >
> https://github.com/geodynamics/specfem3d_globe/pull/472#issuecomment-189102202
>  > >.
>  > >
>  >
>  > --
>  > Dimitri Komatitsch
>  > CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
>  > UPR 7051, Marseille, France http://komatitsch.free.fr
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  >
> <https://github.com/geodynamics/specfem3d_globe/pull/472#issuecomment-189223114>
>  > .
>  >
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/472#issuecomment-189317939>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
