### PR TITLE
adds plotting script

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 259](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/259).

**Comment by danielpeter** [comment]
accept

**Comment by komatits** [comment]
accept

On 10/01/2015 05:10 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 259
> <http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/259>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/444#issuecomment-144756508>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
