### PR TITLE
fixing xsmooth_sem_adios compilation

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 432](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/432). Please fix the problems and push your changes back to your branch danielpeter/specfem3d_globe:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 433](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/433).

**Comment by danielpeter** [comment]
accept

On Sep 13, 2021, at 23:31, buildbot-princeton ***@***.******@***.***>> wrote:


Your changes passed the buildbot test. See build 433<https://urldefense.com/v3/__http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/433__;!!Nmw4Hv0!joihlBaePX5afdrZXjUN340fvG8D5iWm9j4CKG6mnMCEszl40-T0KKE7QdXtW-27EeXZKQ$>.

**Pull request merged**
