### PR TITLE
fix Makefile.in when using ADIOS

### PR DESCRIPTION
**Pull request by wjlei1990**
fix complie flag issues at configure stage when using adios.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Your changes are not mergeable. Please fix the problem and open a new pull-request

**Comment by danielpeter** [comment]
hi Wenjie, 

these flags are rather system dependent. when i compile with ASDF support on other systems (workstation, mac, etc.), these flags change. an easy workaround is to put them into the ASDF_LIBS flag:
``` 
./configure .. --with-asdf ASDF_LIBS=".."
```

still, if you do want to submit this commit to have a specific Makefile setup for summit, you'll have to do a git rebase first.

**Comment by wjlei1990** [comment]
Got you. So you mean adding `-lasdf -lhdf5hl_fortran -lhdf5_hl -lhdf5 -lstdc++` to the `ASDF_LIBS`. I think I can do that. It would be a more portable way.

**Comment by wjlei1990** [comment]
One more questions, I think my updates are commited on the most recent version of `devel` branch. Why do I need to do a rebase?

**Pull request closed without merging**
