### PR TITLE
made src/tomography/sum_kernels.f90 conform to the Fortran95 standard

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 178](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/178).

**Comment by rmodrak** [comment]
Hi Dimitri,

Thank for your help cleaning up the new code as well as all the useful
feedback on github.

I am working on further cleaning up the tokenize subroutine and moving it
to its own file in src/shared.

First though, my priority is to separate the postprocessing utilities from
nonlinear optimization utilities in specfem3d_globe, as I have just done
this in specfem3d.

Best regards,
Ryan

**Comment by komatits** [comment]
accept

On 02/24/2015 04:23 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 178
> <http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/178>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/328#issuecomment-75691907>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
