### PR TITLE
added utils/seizmo_master_containing_Matlab_codes_for_mt2dc_conversion.zip and a comment in utils/strike_dip_rake_to_CMTSOLUTION.c

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 279](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/279).

**Comment by komatits** [comment]
accept

On 25/02/2016 01:54, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 279
> <http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/279>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/469#issuecomment-188539320>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by QuLogic** [comment]
Just so you know, ObsPy provides conversion for moment tensors from/to several different bases and strike/dip/rake.

**Comment by komatits** [comment]
Thanks!

On 25/02/2016 02:15, Elliott Sales de Andrade wrote:
> Just so you know, ObsPy provides conversion for moment tensors from/to
> several different bases and strike/dip/rake.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/pull/469#issuecomment-188545139>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
